### PR TITLE
Add a test to ensure that the default channel isn't anaconda

### PR DESCRIPTION
**Pull request by hmaarrfk**
Closes https://github.com/conda-forge/miniforge/issues/44

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@isuruf this seems to be working for linux, but is breaking the Mac builds? I'm really not sure why it would be though.

**Comment by hmaarrfk** [comment]
@isuruf what do you think about this?

**Comment by hmaarrfk** [comment]
@conda-forge/miniforge any thoughts on this?

**Comment by isuruf** [comment]
Does this we can't add `defaults` channel in if we wanted to?

**Comment by hmaarrfk** [comment]
hmm, good question. let me test locally

**Comment by hmaarrfk** [comment]
You are right, the custom multi channel is overwritten.

**Comment by hmaarrfk** [comment]
Not very ideal.

I added the branding portions in #52 closing this for now as it seems to be a bug in anaconda that may or may not have been fixed recently.

**Pull request closed without merging**
