### PR TITLE
Use powershell + WScript

### LINKED ISSUE #641: Install 24.7.1(x64) on windows10/11 encounter: Failed to run pre_install
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Install 24.7.1(x64) on windows10/11 encounter: Failed to run pre_install
Snipaste_2024-09-10_09-08-26

### Installed packages

```shell
install error
```

### Environment info

```shell
24.7.1
```

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #641

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Do we want to revert the "brownout code" as well? I feel like this is a "minor issue" and I would rather reduce churn since GUI users can press "ignore" on the error and move on.

**Comment by hmaarrfk** [comment]
did you need somebody to test this?

**Comment by jaimergp** [comment]
I tested the script locally by calling it directly and did get my popup and warning. I did not build an installer locally though. I think the brownout code is correct, isn't it? I can test it locally tomorrow.

**Comment by jaimergp** [comment]
Ah, I see. Yea, I don't think it's too valuable. If someone complains, well, the Miniforge versions do work perfectly and that's where we want to direct people to.

**Comment by hmaarrfk** [comment]
Ok thank you, pre-release started:
https://github.com/conda-forge/miniforge/releases/tag/24.7.1-2

**Pull request merged**
