### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by HernandoR**
Since i have looked for command to set mamba as default resolver **dozens of times** , I think it would be ideal to add in the readme document

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
This is the default already, thus I would not include it in the readme anymore.

**Comment by HernandoR** [comment]
Just to be sure: the resolver of `conda` is now by default `libmamba` hence i do not need to do any configuration?

**Comment by xhochy** [comment]
> Just to be sure: the resolver of `conda` is now by default `libmamba` hence i do not need to do any configuration?

Yes.

**Comment by jakirkham** [comment]
Please see [this blogpost]( https://conda.org/blog/2023-11-06-conda-23-10-0-release/ ) for details

**Comment by HernandoR** [comment]
Great !

**Pull request closed without merging**
