### PR TITLE
WIP: Test update script again

### PR DESCRIPTION
**Pull request by hmaarrfk**
Trying to recreate @ocefpaf 's challenges
https://github.com/conda-forge/conda-feedstock/pull/135#issuecomment-915377400

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Thanks for testing it out! I was unable to reproduce it in CIs. Only on my ubuntu box :-/

**Comment by hmaarrfk** [comment]
What version of Ubuntu are you using? I've installed miniforge on quite a few Ubuntu installs without hitting this issue. 

Do you have some customizations that are notable?

**Comment by hmaarrfk** [comment]
Are you able to recreate this on a machine you have access to? I might be able to give a script that tries to go through a whole isntall process:

1. Create a new user
2. Login as the new user.
3. Try to install miniforge
4. Run update
5. Check for errors

That would help me quite a bit.

**Comment by ocefpaf** [comment]
Yep. I can do that.

**Comment by ocefpaf** [comment]
@hmaarrfk I think we can close this one, right?

**Comment by hmaarrfk** [comment]
yes

**Pull request closed without merging**
