### PR TITLE
Update to conda 4.14, cpython 3.10, pypy 3.9

### PR DESCRIPTION
**Pull request by isuruf**
Closes https://github.com/conda-forge/miniforge/issues/323

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@mattip, we are updating base python in miniforge to 3.10. For pypy should we be going for 3.8 or 3.9?

**Comment by mattip** [comment]
I think 3.9 will be supported longer, so might as well use it. I don't remember python-3.9-specific issues for quite a while now.

**Comment by mattip** [comment]
There is a [package conflict](https://github.com/conda-forge/miniforge/runs/7933737372?check_suite_focus=true#step:4:444) for pypy on the mamba builds. I am not sure which package it is, but maybe there is a missing migration somewhere.

**Comment by hmaarrfk** [comment]
mamba itself apparently :D https://github.com/conda-forge/mamba-feedstock/pull/158

**Pull request merged**
