### PR TITLE
Test mamba transmute

### PR DESCRIPTION
**Pull request by wolfv**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wolfv** [comment]
@chrisburr this seems to "work" now but unfortunately there are a bunch of warnings like 

```
warning  libmamba Extracted package cache '/root/miniforge/pkgs/wheel-0.37.1-pyhd8ed1ab_0' has invalid size
warning  libmamba Extracted package cache '/root/miniforge/pkgs/wheel-0.37.1-pyhd8ed1ab_0' has invalid MD5 checksum
warning  libmamba Extracted package cache '/root/miniforge/pkgs/pip-22.0.3-pyhd8ed1ab_0' has invalid size
warning  libmamba Extracted package cache '/root/miniforge/pkgs/pip-22.0.3-pyhd8ed1ab_0' has invalid MD5 checksum
warning  libmamba Extracted package cache '/root/miniforge/pkgs/six-1.16.0-pyh6c4a22f_0' has invalid size
warning  libmamba Extracted package cache '/root/miniforge/pkgs/six-1.16.0-pyh6c4a22f_0' has invalid MD5 checksum
warning  libmamba Extracted package cache '/root/miniforge/pkgs/pycparser-2.21-pyhd8ed1ab_0' has invalid size
warning  libmamba Extracted package cache '/root/miniforge/pkgs/pycparser-2.21-pyhd8ed1ab_0' has invalid MD5 checksum
warning  libmamba Extracted package cache '/root/miniforge/pkgs/idna-3.3-pyhd8ed1ab_0' has invalid size
warning  libmamba Extracted package cache '/root/miniforge/pkgs/idna-3.3-pyhd8ed1ab_0' has invalid MD5 checksum
warning  libmamba Extracted package cache '/root/miniforge/pkgs/colorama-0.4.4-pyh9f0ad1d_0' has invalid size
warning  libmamba Extracted package cache '/root/miniforge/pkgs/colorama-0.4.4-pyh9f0ad1d_0' has invalid MD5 checksum
warning  libmamba Extracted package cache '/root/miniforge/pkgs/charset-normalizer-2.0.12-pyhd8ed1ab_0' has invalid size
warning  libmamba Extracted package cache '/root/miniforge/pkgs/charset-normalizer-2.0.12-pyhd8ed1ab_0' has invalid MD5 checksum
warning  libmamba Extracted package cache '/root/miniforge/pkgs/tqdm-4.62.3-pyhd8ed1ab_0' has invalid size
warning  libmamba Extracted package cache '/root/miniforge/pkgs/tqdm-4.62.3-pyhd8ed1ab_0' has invalid MD5 checksum
warning  libmamba Extracted package cache '/root/miniforge/pkgs/pyopenssl-22.0.0-pyhd8ed1ab_0' has invalid size
warning  libmamba Extracted package cache '/root/miniforge/pkgs/pyopenssl-22.0.0-pyhd8ed1ab_0' has invalid MD5 checksum
warning  libmamba Extracted package cache '/root/miniforge/pkgs/urllib3-1.26.8-pyhd8ed1ab_1' has invalid size
warning  libmamba Extracted package cache '/root/miniforge/pkgs/urllib3-1.26.8-pyhd8ed1ab_1' has invalid MD5 checksum
warning  libmamba Extracted package cache '/root/miniforge/pkgs/requests-2.27.1-pyhd8ed1ab_0' has invalid size
warning  libmamba Extracted package cache '/root/miniforge/pkgs/requests-2.27.1-pyhd8ed1ab_0' has invalid MD5 checksum
```

because the checksums do not match up with the one from the repository... 
It's a bit of a mess. We could downgrade those logs to info or hide them if the package extension differs (.conda vs .tar.bz2)...

**Comment by hmaarrfk** [comment]
why would the extracted .conda packages be any different than the extracted .tar.bz2 packages?

**Comment by wolfv** [comment]
The sha256 of the original package is different and that value is saved to check if it's actually the same package

**Comment by hmaarrfk** [comment]
So when i read the error, i should interpret it as:
```
/root/miniforge/pkgs/pip-22.0.3-pyhd8ed1ab_0 was extracted from /root/miniforge/pkgs/pip-22.0.3-pyhd8ed1ab_0.conda .
However, the /root/miniforge/pkgs/pip-22.0.3-pyhd8ed1ab_0.conda file has a different sha256 than the one from /root/miniforge/pkgs/pip-22.0.3-pyhd8ed1ab_0.tar.bz2
```

**Comment by jaimergp** [comment]
This should have been fixed in https://github.com/conda/constructor/pull/692, so I am closing here. We also have tests with transmutation in constructor since https://github.com/conda/constructor/pull/605.

**Pull request closed without merging**
