### PR TITLE
turn on keep_pkgs in construct.yaml

### PR DESCRIPTION
**Pull request by Shenggan**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

related issue #30

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Does this address #21 ?

**Comment by Shenggan** [comment]
I think so. 

> Does this address #21 ?

**Comment by hmaarrfk** [comment]
Could you add a test or a comment (in the code) as to why this is necessary.

And if you would like this to be merged first, then let me now, we will have to bump the version somehow.

**Comment by Shenggan** [comment]
I add a comment in the code. And it's fine to fix it when next version release.

**Comment by scopatz** [comment]
@Shenggan - can your comment address the hardlinking issue please? Thanks!

**Comment by hmaarrfk** [comment]
A few words specifically referring to the issue
https://github.com/conda-forge/miniforge/issues/21

would be good.

**Comment by Shenggan** [comment]
@scopatz @hmaarrfk Thanks for suggestion.

**Comment by scopatz** [comment]
This passed before and the only change was to a comment, so I don't know why it failed.  Merging is very likely safe.

**Pull request merged**
