### PR TITLE
Provide Miniforge3+mamba as Mambaforge3

### PR DESCRIPTION
**Pull request by xhochy**
Proposal for #23 

Currently this is a hard rename of the CI jobs to keep the matrix, I would though reintroduce `Miniforge` again before we merge this.

### CODE REVIEW

**Comment by wolfv** [comment]
@SylvainCorlay just did the same #69 

what now!? :)

**Comment by xhochy** [comment]
:D I prefer my `construct.yaml` otherwise I'm fine with @SylvainCorlay 's PR.

**Comment by wolfv** [comment]
maybe you can find hte fix for windows .. sylvain is on a lunch break :D

**Comment by SylvainCorlay** [comment]
lol @xhochy what are the chances we would do this a few minutes apart.

**Pull request closed without merging**
