### PR TITLE
Standardize macOS naming in README.md

### PR DESCRIPTION
**Pull request by amorehead**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Thank you! This is a welcome change, but you seem to only be adding "more variants".

**Comment by amorehead** [comment]
Ah, good point. I'll fix that now.

**Comment by hmaarrfk** [comment]
Try to go even further, there are a few references to `OS X`

**Comment by amorehead** [comment]
I think I got most of them, the only ones I can't update are the download URLs.

**Comment by hmaarrfk** [comment]
> I think I got most of them, the only ones I can't update are the download URLs.

Actually reverted the one to the "filename previews". I guess for the things that allude to the download names we can't really change, but for what refers to the operating system in prose we can.

**Comment by hmaarrfk** [comment]
Thanks!

**Pull request merged**
