### PR TITLE
Switch to constructor >=3.4.2

### PR DESCRIPTION
**Pull request by dbast**
~~The next soon to be [happening](https://github.com/conda/constructor/issues/577) constructor release contains lots of [changes](https://github.com/conda/constructor/tree/main/news).~~  Released

~~Pinning the current stable version allows to later consciously unpin it again, while the unpin PR artefacts can serve as test point to check that all the installers continue to work fine, before tagging a new release.~~

Requiring constructor ~~>=3.4.1~~ >=3.4.2 to see how it builds.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Lets leave this out here for abit. I'm somewhat interested in trying the new release. We've use development releases before with success.

**Comment by hmaarrfk** [comment]
But it might be good to "merge" this quickly when problems do arise.

**Comment by dbast** [comment]
new version will be available soon https://github.com/conda-forge/constructor-feedstock/pull/66

**Comment by hmaarrfk** [comment]
It might be worth a new release. we would have to pin setuptools to 65.

**Comment by dbast** [comment]
looks like constructor 3.4.1 was not available for windows yet, due to channel mirroring not finished.

**Comment by hmaarrfk** [comment]
Well maybe this is going better than expected. I do want to go through the logs and ensure that setup tools 65 is installed.

Downgrades are painful.

**Comment by hmaarrfk** [comment]
I've pinned setuptools and trying to update conda. We could also try to update mamba
https://github.com/conda-forge/miniforge/pull/406

**Comment by hmaarrfk** [comment]
Shall we try to update mamba as well? I guess my point is that i'll try to create a release as soon as we merge this, so it would be good to get a few of these "updates" done at once. With the conda version change, we at least get a "visible" change in the version number for Miniforge3 and Mambaforge!

**Comment by hmaarrfk** [comment]
ok, lets wait, but our CIs test the install process (in batch mode) so presumably we were OK.

boa needs a new release, otherwise we can't install mamba 1.2.0 https://github.com/conda-forge/boa-feedstock/blob/main/recipe/meta.yaml#L27

**Comment by hmaarrfk** [comment]
Did you want to downgrade the conda version to something particular?

**Comment by dbast** [comment]
Here we go https://github.com/conda-forge/constructor-feedstock/pull/67

**Comment by hmaarrfk** [comment]
@dbast i'm taking your rocket as approval. Lets try to start the builds.

**Pull request merged**
