### PR TITLE
Create a first version of the builder

### PR DESCRIPTION
**Pull request by hmaarrfk**
Waiting on: https://github.com/conda-forge/conda-forge.github.io/pull/922

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
Maybe you plan to address this later but just in case: I don't think the installer will work on an `arm64` machine since it's built from a host Linux x86_64 machine. The way to do it is to construct from an `arm64` Docker image. See https://github.com/conda-forge/conda-forge.github.io/issues/871#issuecomment-553198695

Sorry if you already know that.

**Comment by hmaarrfk** [comment]
the archiconda installer was build on an x86 machine :/

**Comment by hadim** [comment]
Hum interesting... When I tried to build an installer from x86 and executed it on the RPi 4 I got the following error:

```
Archiconda-0.3.0-Linux-aarch64.sh: line 259: /home/ubuntu/archiconda/conda.exe: cannot execute binary file: Exec format error
ERROR: could not extract tar starting at offset 000000000000011467+9231072+2
```

See https://github.com/conda-forge/conda-forge.github.io/issues/871#issuecomment-553197998

When building it using the `condaforge/linux-anvil-aarch64` Docker image, it worked.

Now if you tell me your last Archiconda installer was built on x86 I am confused because your installer worked on RPi 4...

Once you have the first release I can try it on RPi 4 and see if it works.

@isuruf any thought about that?

**Comment by hmaarrfk** [comment]
I think constructor can be used to create an installer for an other architecture. I think all constructor does is extract files and sets permissions.

**Comment by hadim** [comment]
Yes, but my understanding is the installer is an executable that is platform-specific.

**Comment by hmaarrfk** [comment]
I could have sworn that I built them on my laptop without a docker image. I just used the command I documented 

https://github.com/Archiconda/build-tools/tree/master/installer

**Comment by hmaarrfk** [comment]
I guess I'll have to spin up images to test the installer then....

**Comment by hadim** [comment]
I just try again with:

```yaml
name: Miniforge3
version: 0.1.0

channels:
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/anaconda
  # This will continue to be a dependency until the compilers are
  # moved to conda-forge or to anaconda
  - https://conda.anaconda.org/c4aarch64   [linux-aarch64]

write_condarc: True

specs:
  - python >=3,<3.8
  - conda
  - pip
```

When executing the installer on the RPi 4, I got the same error but the installer works fine on the host machine.

Yes make the first release and I'll test it. But I don't understand how an executable file can be executed on both x86 and aarch64.

**Comment by hmaarrfk** [comment]
yeah, i just tried it on my local machine too. I was really surprised it worked.

**Comment by hadim** [comment]
Are you sure you didn't use https://github.com/Archiconda/build-tools/blob/master/docker-images/Dockerfile to build Archiconda?

**Comment by hadim** [comment]
Here is the Docker image I used to build my own installer: https://github.com/hadim/docker-conda-arm64

Feel free to use it with https://docs.travis-ci.com/user/docker/

**Comment by hmaarrfk** [comment]
I guess I would have to use `condaforge/linux-anvil-aarch64`, but doing docker in docker is annoying.....

**Comment by hadim** [comment]
If you merge this PR. I can submit a new one with Docker support.

**Pull request merged**
