### PR TITLE
Miniforge with PyPy

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@scopatz, @hadim, @hmaarrfk, what do you think of the name `miniforge-pypy3`?

**Comment by hmaarrfk** [comment]
does it really need to be specified? this only chagnes the base environment right?

**Comment by isuruf** [comment]
@hmaarrfk, miniconda had 2 variants `miniconda2`, `miniconda3` which implied what python version was used. That's why I wanted to have a different name

**Comment by hmaarrfk** [comment]
Final question, do we have a plan to stop supporting this variant? I wouldn't want this to be a blocker seeing as the user can easily create their own environment with pypy installed.

**Comment by isuruf** [comment]
@hmaarrfk, we can always mark the travis builds as `allow_failures`, but please feel free to ping me if there's any issue.

**Comment by hmaarrfk** [comment]
Got it

**Pull request merged**
