### PR TITLE
remove notice about work being very experimental

### PR DESCRIPTION
**Pull request by ilanschnell**
I have tested the current installer on an aarch64 system and didn't find any problems with it.  I was able to install many libraries using conda and also able to create a Python 3.8 environment (and install libraries therein).  Having a note saying "This work is still very experimental." will discourage many users to give miniforge a try.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
The problem is that many packages depend on matplotlib and matplotlib depends on the graphics stack.

I would like a link to the migration status instead.

**Comment by jakirkham** [comment]
Should add I’m not aware of any testing of the installer to the level that Anaconda or Miniconda are tested.

**Comment by rgommers** [comment]
So a bit of context: we did not discover this repo at all in multiple searches, and therefore wasted time on Archiconda until @scopatz pointed us to this repo. Both upgrading to latest versions and building a new installer by @ilanschnell worked without any problems. We also tested this on several systems including installing the core SciPy stack, `spyder-kernels`, `ipykernel` and some more exotic packages.

At this point it seems clear that usage and effort should go here rather than Archiconda. So it would be good to encourage usage and contributions. While at the same time pointing to what's not yet done. Removing a "highly experimental" label seems like a necessary step in this process. But of course there's more to do.

**Comment by rgommers** [comment]
So concrete suggestions for what you want to see is useful. Pointing to porting status. And what else?

**Comment by isuruf** [comment]
One orthogonal issue (regarding advertising the package) is that we don't have a perma link, https://github.com/conda-forge/miniforge/issues/11. Help in making it stable is appreciated.

**Comment by hmaarrfk** [comment]
"Wasted time with Archiconda" seems a little harsh to me if it did enable the successful install of a conda powered python...

To my knowledge, both Archiconda and miniforge are the same thing but different branding.

If you want to optimize the wording so that it is found by Google, then that would be super appreciated as well.

**Comment by ilanschnell** [comment]
Yes, Archiconda and miniforge are basically the same thing.  However, as miniforge is under the conda-forge brand, which is already very successful and recognized, I would prefer usage and effort here.

**Comment by scopatz** [comment]
Hi All, I think we are all of one mind and purpose here, which is to provide installers for the various platforms.  

@ilanschnell, Can you please add a link to https://conda-forge.org/status/ and a message about the linux-aarch64 migration specifically.  I think we also need to follow this up with a PR or two into the documetation repo (both in the docs proper and on the landing page) explaining miniforge and directing users on how to use it.

**Comment by rgommers** [comment]
> "Wasted time with Archiconda" seems a little harsh to me if it did enable the successful install of a conda powered python

@hmaarrfk no criticism of the effort that went into Archiconda intended of course! It's just that that effort seems abandoned (no repo in https://github.com/Archiconda has seen an update since April 2019) so we'd much rather focus efforts here.

Also note that our aim is not to install on any particular machine right now, but to have an installation method that is stable and can be updated for months/years to come. So from that perspective, yeah Archiconda was a distraction.

**Comment by hmaarrfk** [comment]
@rgommers links to miniforge have been added to Archiconda.

Ultimately, you should always run `conda update --all` on the base environment no matter how you install it. That hasn't changed, so it made my abitions to keep Archiconda updated very small seeing as the Installer from April 2019 still works today.

**Comment by scopatz** [comment]
Thanks @hmaarrfk!

**Comment by rgommers** [comment]
> @rgommers links to miniforge have been added to Archiconda.

Thanks!

> Ultimately, you should always run `conda update --all` on the base environment no matter how you install it.

I'm not sure that's best practice. Just checked with @ilanschnell here, neither of us have ever done this nor do we think it should be needed.

**Comment by hmaarrfk** [comment]
ok. i think the main goal of this PR has been reached. 

I'm going to merge this, so I can update documentation.

**Comment by rgommers** [comment]
> @ilanschnell, Can you please add a link to https://conda-forge.org/status/ and a message about the linux-aarch64 migration specifically. I think we also need to follow this up with a PR or two into the documetation repo (both in the docs proper and on the landing page) explaining miniforge and directing users on how to use it.

This is still open, will be followed up on in a separate PR.

**Comment by ilanschnell** [comment]
I'm happy to see `x86_64` and `ppc64le` installers!  I've added a few sentences about miniforge to the conda-forge documentation: https://github.com/conda-forge/conda-forge.github.io/pull/978

**Pull request merged**
