### PR TITLE
Build docker image as part of the installer build

### PR DESCRIPTION
**Pull request by xhochy**
By combining both, we can easily release version tagged docker images.

### CODE REVIEW

**Comment by jakirkham** [comment]
Should we include CentOS ones as well? Wondering if we could use these as base images to derive from in docker-images

**Comment by isuruf** [comment]
If we are going to include more images such as CentOS, then I'm not in favour of merging this. We can have a CI script here that triggers a build on docker-images.

**Comment by jakirkham** [comment]
In that case shouldn’t we just have a script to trigger a build on docker-images now? This image is from there IIRC

I think the one challenge is we pin the Miniforge version in docker-images. So we would need a way to update that through this build trigger somehow. Maybe we could separate that information into a file we overwrite?

**Comment by xhochy** [comment]
I'm wondering whether it would be better whether to use a separate repo for the miniforge images (neither miniforge nor docker-images). Then we could separate CI but still keep the versioning aligned with miniforge.

**Comment by isuruf** [comment]
@xhochy, sounds good to me. We then don't even have to build a docker image for mambaforge and just include mamba by default in miniforge image.

**Comment by xhochy** [comment]
> @xhochy, sounds good to me. We then don't even have to build a docker image for mambaforge and just include mamba by default in miniforge image.

I would rather keep the naming consistent. This will otherwise be confusing to a lot of endusers.

**Comment by jakirkham** [comment]
Should this be closed out? Looks like these changes have been moved to a new repo with PR ( https://github.com/conda-forge/miniforge-images/pull/2 )

**Comment by xhochy** [comment]
> Should this be closed out? Looks like these changes have been moved to a new repo with PR ( [conda-forge/miniforge-images#2](https://github.com/conda-forge/miniforge-images/pull/2) )

Yes.

**Pull request closed without merging**
