### PR TITLE
Update to python 3.11

### PR DESCRIPTION
**Pull request by hmaarrfk**
Closes https://github.com/conda-forge/miniforge/issues/598
Closes #603 

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
Merging and releasing a new miniforge will require macOS 10.13, so we need to make some changes in the README and maybe have an announcement.

**Comment by mbargull** [comment]
> Merging and releasing a new miniforge will require macOS 10.13, so we need to make some changes in the README and maybe have an announcement.

I've added this to the tables in https://github.com/conda-forge/miniforge/pull/603/commits/d2f7b3c29150d50fcc8eeadbee930fb694972217 .
Does that work for you?

So, a small announcement saying something like the following?
> As announced in https://conda-forge.org/news/2023/08/24/bumping-minimum-macos-version-to-1013/ , the minimum supported macOS version has been raised to in 10.13 via https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5829 for newly built packages and via https://github.com/conda-forge/miniforge/pull/603 for the Miniforge installers.

(PR links could be replaced with dates/versions in case they are deemed to technical.)

**Comment by hmaarrfk** [comment]
> Merging and releasing a new miniforge will require macOS 10.13, so we need to make some changes in the README and maybe have an announcement.

Great catch!

**Comment by hmaarrfk** [comment]
It seems that there is more traction on #603. closing in favor of Python 3.12.

**Pull request closed without merging**
