### PR TITLE
Use .conda packages for smaller miniforge

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by scopatz** [comment]
Very much in favor of this :+1:

**Comment by isuruf** [comment]
Needs a new release of cph. https://github.com/conda/conda-package-handling/issues/70

**Comment by dhirschfeld** [comment]
It looks like this is unblocked: https://github.com/conda/conda-package-handling/releases/tag/1.7.2

Would love to see this in as anything which speeds up CI can have a huge productivity boost!

**Comment by hmaarrfk** [comment]
transmutting is rather slow locally on windows. Not sure if it is due to anything in particular.

**Comment by jakirkham** [comment]
> It looks like this is unblocked: https://github.com/conda/conda-package-handling/releases/tag/1.7.2
> 
> Would love to see this in as anything which speeds up CI can have a huge productivity boost!

Looks like we already built that version ( https://github.com/conda-forge/conda-package-handling-feedstock/pull/50 ). Maybe I'm missing something though.

**Comment by chrisburr** [comment]
This was done in https://github.com/conda-forge/miniforge/pull/260

**Pull request closed without merging**
