### PR TITLE
add brew installation instructions

### PR DESCRIPTION
**Pull request by domoritz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by hmaarrfk — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Dominik! 😄

**Comment by domoritz** [comment]
Once https://github.com/Homebrew/homebrew-cask/pull/97538 is merged, ARM should work out of the box. 

I wonder whether it would be possible to automatically update the brew formula when there is a new release or whether you want to make it part of the release process. There is a command-line tool for making updates: https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask.

**Comment by domoritz** [comment]
Just confirmed that `brew install miniforge` works out of the box on a MacBook with M1.

**Comment by hmaarrfk** [comment]
is it running everything through rosetta? or native?

**Comment by domoritz** [comment]
It's installing native versions of packages (e.g. Python).

**Pull request merged**
